# Other configurations...
title: My FLEXORA Site
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write description here.
baseurl: "/index.html" # the subpath of your site, e.g. /blog
url: "HTTP://FLEXORA-ai.com" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
theme: jekyll-theme-primer # Your theme

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal list.
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules/        # Make sure this is present
  - FLEXORA-BE/          # Add this line to exclude the entire backend folder
  # Or if you only want to exclude node_modules within FLEXORA-BE:
  # - FLEXORA-BE/node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  # Add other files/folders to exclude if needed

# Plugins (might already be here)
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  # Other plugins...
